var _yt_www={};(function(g){var window=this;var baa,caa,Ba,Fa,eb,kaa,fb,gb,hb,ib,nb,laa,ob,maa,yb,naa,vb,Hb,Yb,ac,ec,gc,Kc,$c,waa,yaa,xaa,zaa,Aaa,nd,qd,Eaa,Faa,Daa,Gaa,ce,ee,de,Jaa,Kaa,Laa,Maa,Naa,ie,pe,oe,je,Qaa,we,te,ue,Paa,Ce,le,xe,Be,ne,ge,fe,he,se,ye,Ae,Ee,Re,Ue,Xe,Ze,ef,ff,Bf,Cf,Waa,Kf,Lf,Xaa,Of,Sf,Qf,Pf,Yaa,Vf,Wf,Zf,ag,bg,cg,fg,eg,hg,dg,ig,Xf,$f,dba,jg,kg,eba,fba,qg,sg,ug,Bg,gba,Gg,Eg,iba,Jg,Hg,Ig,Ng,hba,Lg,lba,kba,jba,Tg,Rg,Ug,Wg,mba,nba,Xg,Yg,ch,gh,hh,ih,lh,mh,nh,tba,uba,dh,fh,bh,sba,eh,xba,wba,qh,rh,sh,pa,aaa;
g.ca=function(a){return function(){return g.ba[a].apply(this,arguments)}};
g.da=function(a){return void 0!==a};
g.m=function(a,b,c){a=a.split(".");c=c||g.ea;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&g.da(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};
g.p=function(a,b){for(var c=a.split("."),d=b||g.ea,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};
g.fa=function(){};
g.ga=function(a){a.getInstance=function(){return a.tc?a.tc:a.tc=new a}};
g.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};
g.ia=function(a){return"array"==g.ha(a)};
g.ja=function(a){var b=g.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};
g.ka=function(a){return"string"==typeof a};
g.la=function(a){return"number"==typeof a};
g.ma=function(a){return"function"==g.ha(a)};
g.oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
g.qa=function(a){return a[pa]||(a[pa]=++aaa)};
baa=function(a,b,c){return a.call.apply(a.bind,arguments)};
caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
g.q=function(a,b,c){g.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return g.q.apply(null,arguments)};
g.r=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};
g.t=function(a,b){function c(){}
c.prototype=b.prototype;a.K=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.vU=function(a,c,f){for(var k=Array(arguments.length-2),l=2;l<arguments.length;l++)k[l-2]=arguments[l];return b.prototype[c].apply(a,k)}};
g.ra=function(a){g.ra[" "](a);return a};
g.sa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,g.sa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};
g.ta=function(a,b){return 0==a.lastIndexOf(b,0)};
g.ua=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};
g.va=function(a){return(0,window.encodeURIComponent)(String(a))};
g.wa=function(a){return(0,window.decodeURIComponent)(a.replace(/\+/g," "))};
g.xa=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};
g.ya=function(a,b){return-1!=a.indexOf(b)};
g.za=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
g.Ca=function(a,b){for(var c=0,d=(0,g.Aa)(String(a)).split("."),e=(0,g.Aa)(String(b)).split("."),f=Math.max(d.length,e.length),k=0;0==c&&k<f;k++){var l=d[k]||"",n=e[k]||"",u=RegExp("(\\d*)(\\D*)","g"),w=RegExp("(\\d*)(\\D*)","g");do{var H=u.exec(l)||["","",""],L=w.exec(n)||["","",""];if(0==H[0].length&&0==L[0].length)break;c=Ba(0==H[1].length?0:(0,window.parseInt)(H[1],10),0==L[1].length?0:(0,window.parseInt)(L[1],10))||Ba(0==H[2].length,0==L[2].length)||Ba(H[2],L[2])}while(0==c)}return c};
Ba=function(a,b){return a<b?-1:a>b?1:0};
g.Ea=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c)>>>0;return b};
Fa=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
g.Ga=function(a){var b=g.ka(void 0)?g.za(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};
g.Ia=function(a,b,c){b=g.Ha(a,b,c);return 0>b?null:g.ka(a)?a.charAt(b):a[b]};
g.Ha=function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};
g.Ka=function(a,b){return 0<=(0,g.Ja)(a,b)};
g.Na=function(a,b){var c=(0,g.Ja)(a,b),d;(d=0<=c)&&g.La(a,c);return d};
g.La=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};
g.Oa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
g.Pa=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(g.ja(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var k=0;k<f;k++)a[e+k]=d[k]}else a.push(d)}};
g.Qa=function(a){return function(){return a}};
g.Ra=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};
g.Sa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
g.Ta=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
g.Ua=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};
g.Va=function(a){for(var b in a)return!1;return!0};
g.Wa=function(a,b){b in a&&delete a[b]};
g.Xa=function(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
g.Ya=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
g.$a=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Za.length;f++)c=Za[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
g.bb=function(a){return g.ya(g.ab,a)};
g.cb=function(){return g.bb("Trident")||g.bb("MSIE")};
g.db=function(){return(g.bb("Chrome")||g.bb("CriOS"))&&!g.bb("Edge")};
eb=function(a){g.ea.setTimeout(function(){throw a;},0)};
kaa=function(){var a=g.ea.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!g.bb("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,g.q)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);
b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});
if("undefined"!==typeof a&&!g.cb()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(g.da(c.next)){c=c.next;var a=c.wp;c.wp=null;a()}};
return function(a){d.next={wp:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};
window.document.documentElement.appendChild(b)}:function(a){g.ea.setTimeout(a,0)}};
fb=function(a,b,c){this.F=c;this.B=a;this.D=b;this.C=0;this.A=null};
gb=function(a,b){a.D(b);a.C<a.F&&(a.C++,b.next=a.A,a.A=b)};
hb=function(){this.C=this.A=null};
ib=function(){this.next=this.scope=this.ne=null};
nb=function(a,b){jb||laa();kb||(jb(),kb=!0);var c=lb,d=mb.get();d.set(a,b);c.C?c.C.next=d:c.A=d;c.C=d};
laa=function(){if(g.ea.Promise&&g.ea.Promise.resolve){var a=g.ea.Promise.resolve(void 0);jb=function(){a.then(ob)}}else jb=function(){var a=ob;
!g.ma(g.ea.setImmediate)||g.ea.Window&&g.ea.Window.prototype&&!g.bb("Edge")&&g.ea.Window.prototype.setImmediate==g.ea.setImmediate?(pb||(pb=kaa()),pb(a)):g.ea.setImmediate(a)}};
ob=function(){for(var a;a=lb.remove();){try{a.ne.call(a.scope)}catch(b){eb(b)}gb(mb,a)}kb=!1};
g.qb=function(){this.Ld=this.Ld;this.Jb=this.Jb};
g.tb=function(a,b){g.rb(a,g.r(g.sb,b))};
g.rb=function(a,b){a.Ld?b.call(void 0):(a.Jb||(a.Jb=[]),a.Jb.push(g.da(void 0)?(0,g.q)(b,void 0):b))};
g.sb=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
g.ub=function(a){g.qb.call(this);this.D=1;this.C=[];this.B=0;this.A=[];this.rd={};this.F=!!a};
maa=function(a,b,c){nb(function(){a.apply(b,c)})};
g.xb=function(a){vb(g.wb,arguments)};
g.v=function(a,b){return a in g.wb?g.wb[a]:b};
g.zb=function(a,b){g.ma(a)&&(a=yb(a));return window.setTimeout(a,b)};
g.Ab=function(a,b){g.ma(a)&&(a=yb(a));return window.setInterval(a,b)};
g.Bb=function(a){window.clearTimeout(a)};
g.Cb=function(a){window.clearInterval(a)};
yb=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw g.Db(b),b;}}:a};
g.Db=function(a,b,c,d,e){var f=g.p("yt.logging.errors.log");f?f(a,b,c,d,e):(f=g.v("ERRORS",[]),f.push([a,b,c,d,e]),g.xb("ERRORS",f))};
naa=function(a,b,c,d,e){var f=!1;if(g.wb.Ko&&g.wb.Ko.log_window_onerror_fraction&&Math.random()<g.wb.Ko.log_window_onerror_fraction)f=!0;else for(var k=window.document.getElementsByTagName("script"),l=0,n=k.length;l<n;l++)if(0<k[l].src.indexOf("/debug-")){f=!0;break}f&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),g.Db(e))};
g.Fb=function(a){return a in g.Eb};
g.Gb=function(a,b,c){var d=b||{};if(a=a in g.Eb?g.Eb[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});
return a};
vb=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
g.x=function(a,b,c){var d=Hb();if(d){var e=d.subscribe(a,function(){if(!Ib||Ib!=e){var d=arguments,k;k=function(){Jb[e]&&b.apply(c||window,d)};
try{Kb[a]?k():g.zb(k,0)}catch(l){g.Db(l)}}},c);
Jb[e]=!0;Lb[a]||(Lb[a]=[]);Lb[a].push(e);return e}return 0};
g.Mb=function(a){var b=Hb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,g.y)(a,function(a){b.unsubscribeByKey(a);delete Jb[a]}))};
g.z=function(a,b){var c=Hb();return c?c.publish.apply(c,arguments):!1};
g.Nb=function(a,b){Kb[a]=!0;var c=Hb(),c=c?c.publish.apply(c,arguments):!1;Kb[a]=!1;return c};
Hb=function(){return g.p("yt.pubsub.instance_")};
g.Ob=function(){return!!g.p("yt.scheduler.instance")};
g.Pb=function(a,b){(0,window.isNaN)(b)&&(b=void 0);var c=g.p("yt.scheduler.instance.addJob");return c?c(a,1,b):void 0===b?(a(),window.NaN):g.zb(a,b||0)};
g.Qb=function(a,b){return g.Pb(a,b)};
g.Sb=function(a){if(!(0,window.isNaN)(a)){var b=g.p("yt.scheduler.instance.cancelJob");b?b(a):g.Bb(a)}};
g.Tb=function(a){for(var b=0,c=a.length;b<c;b++)g.Sb(a[b])};
g.Ub=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.G=d?yb(d):null;this.F=e?yb(e):null;this.D=[];this.A=this.C=0};
g.Wb=function(a){g.Sb(a.C);a.C=g.Qb((0,g.q)(a.init,a))};
g.Zb=function(a){a.name in Xb&&Yb(a.name);Xb[a.name]={reqs:[],disable:(0,g.q)(a.disable,a)};(0,g.y)(a.deps,function(b){if(!(b in Xb))throw Error("Module "+b+" required by "+a.name);Xb[b].reqs.push(a.name)});
a.enable()};
Yb=function(a){if(a in Xb){var b=Xb[a];(0,g.y)(b.reqs,function(a){Yb(a)});
try{b.disable()}catch(c){}delete Xb[a]}};
ac=function(){this.A="";this.C=$b};
g.bc=function(a){return a instanceof ac&&a.constructor===ac&&a.C===$b?a.A:"type_error:Const"};
g.cc=function(a){var b=new ac;b.A=a;return b};
ec=function(){this.A="";this.C=dc};
g.fc=function(a){if(a instanceof ec&&a.constructor===ec&&a.C===dc)return a.A;g.ha(a);return"type_error:SafeStyle"};
gc=function(a){var b=new ec;b.A=a;return b};
g.hc=function(a){var b="",c;for(c in a){if(!/^[-_a-zA-Z0-9]+$/.test(c))throw Error("Name allows only [-_a-zA-Z0-9], got: "+c);var d=a[c];if(null!=d){if(d instanceof ac)d=g.bc(d);else if(oaa.test(d)){for(var e=!0,f=!0,k=0;k<d.length;k++){var l=d.charAt(k);"'"==l&&f?e=!e:'"'==l&&e&&(f=!f)}e&&f||(d="zClosurez")}else d="zClosurez";b+=c+":"+d+";"}}return b?gc(b):paa};
g.jc=function(){this.A="";this.C=ic};
g.kc=function(a){if(a instanceof g.jc&&a.constructor===g.jc&&a.C===ic)return a.A;g.ha(a);return"type_error:SafeUrl"};
g.mc=function(a){if(a instanceof g.jc)return a;a=a.Mf?a.Oe():String(a);qaa.test(a)||(a="about:invalid#zClosurez");return g.lc(a)};
g.lc=function(a){var b=new g.jc;b.A=a;return b};
g.oc=function(){this.A="";this.C=nc};
g.pc=function(a){if(a instanceof g.oc&&a.constructor===g.oc&&a.C===nc)return a.A;g.ha(a);return"type_error:TrustedResourceUrl"};
g.rc=function(){this.A="";this.B=qc;this.C=null};
g.sc=function(a){if(a instanceof g.rc&&a.constructor===g.rc&&a.B===qc)return a.A;g.ha(a);return"type_error:SafeHtml"};
g.uc=function(a){if(a instanceof g.rc)return a;var b=null;a.tm&&(b=a.vg());a=g.xa(a.Mf?a.Oe():String(a));return g.tc(a,b)};
g.xc=function(a,b,c){if(!vc.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toUpperCase()in raa)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");return g.wc(a,b,c)};
g.yc=function(a){function b(a){g.ia(a)?(0,g.y)(a,b):(a=g.uc(a),d+=g.sc(a),a=a.vg(),0==c?c=a:0!=a&&c!=a&&(c=null))}
var c=0,d="";(0,g.y)(arguments,b);return g.tc(d,c)};
g.tc=function(a,b){var c=new g.rc;c.A=a;c.C=b;return c};
g.wc=function(a,b,c){var d=null,e,f="";if(b)for(e in b){if(!vc.test(e))throw Error('Invalid attribute name "'+e+'".');var k=b[e];if(null!=k){var l,n=a;l=e;if(k instanceof ac)k=g.bc(k);else if("style"==l.toLowerCase()){if(!g.oa(k))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof k+" given: "+k);k instanceof ec||(k=g.hc(k));k=g.fc(k)}else{if(/^on/i.test(l))throw Error('Attribute "'+l+'" requires goog.string.Const value, "'+k+'" given.');if(l.toLowerCase()in
saa)if(k instanceof g.oc)k=g.pc(k);else if(k instanceof g.jc)k=g.kc(k);else if(g.ka(k))k=g.mc(k).Oe();else throw Error('Attribute "'+l+'" on tag "'+n+'" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+k+'" given.');}k.Mf&&(k=k.Oe());l=l+'="'+g.xa(String(k))+'"';f+=" "+l}}e="<"+a+f;null!=c?g.ia(c)||(c=[c]):c=[];!0===taa[a.toLowerCase()]?e+=">":(d=g.yc(c),e+=">"+g.sc(d)+"</"+a+">",d=d.vg());(a=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(a)?d=0:d=null);return g.tc(e,d)};
g.zc=function(a,b){a.innerHTML=g.sc(b)};
g.Ac=function(a,b){var c;c=b instanceof g.jc?b:g.mc(b);a.href=g.kc(c)};
g.A=function(a,b){return a?a.dataset?a.dataset[g.Bc(b)]:a.getAttribute("data-"+b):null};
g.Cc=function(a,b){return a?a.dataset?g.Bc(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};
g.Bc=function(a){return Dc[a]||(Dc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};
g.Fc=function(a,b){var c=g.Ec(a);window.spf.script.load(a,c,b)};
g.Gc=function(a,b){var c=g.Ec(a);window.spf.script.ignore(c,b)};
g.Ec=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(uaa,""),b=b.replace(vaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};
g.Hc=function(a){return g.v("EXPERIMENT_FLAGS",{})[a]};
g.Ic=function(a,b){g.bc(a);g.bc(a);return g.tc(b,null)};
g.Jc=function(){return g.bb("iPhone")&&!g.bb("iPod")&&!g.bb("iPad")};
Kc=function(){var a=g.ea.document;return a?a.documentMode:void 0};
g.Nc=function(a){return Lc[a]||(Lc[a]=0<=g.Ca(g.Mc,a))};
g.Pc=function(a){return Number(g.Oc)>=a};
g.Qc=function(a){return eval("("+a+")")};
g.Rc=function(a,b,c,d,e,f,k){var l="";a&&(l+=a+":");c&&(l+="//",b&&(l+=b+"@"),l+=c,d&&(l+=":"+d));e&&(l+=e);f&&(l+="?"+f);k&&(l+="#"+k);return l};
g.Sc=function(a){return a?(0,window.decodeURI)(a):a};
g.Uc=function(a,b){return b.match(g.Tc)[a]||null};
g.Vc=function(a){return g.Sc(g.Uc(3,a))};
g.Wc=function(a){a=a.match(g.Tc);return g.Rc(null,null,null,null,a[5],a[6],a[7])};
g.Xc=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};
g.Yc=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
g.Zc=function(a,b,c){if(g.ia(b))for(var d=0;d<b.length;d++)g.Zc(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",g.va(b))};
$c=function(a,b){for(var c in b)g.Zc(c,b[c],a);return a};
g.ad=function(a){a=$c([],a);a[0]="";return a.join("")};
g.bd=function(a,b){return g.Yc($c([a],b))};
g.cd=function(a){"?"==a.charAt(0)&&(a=a.substr(1));a=a.split("&");for(var b={},c=0,d=a.length;c<d;c++){var e=a[c].split("=");if(1==e.length&&e[0]||2==e.length){var f=g.wa(e[0]||""),e=g.wa(e[1]||"");f in b?g.ia(b[f])?g.Pa(b[f],e):b[f]=[b[f],e]:b[f]=e}}return b};
g.dd=function(a,b){var c,d=b||{},e=a.split("#",2);c=e[0];var e=1<e.length?"#"+e[1]:"",f=c.split("?",2);c=f[0];var f=g.cd(f[1]||""),k;for(k in d)f[k]=d[k];return g.bd(c,f)+e};
waa=function(a){a=g.ed(a);return g.fd(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
g.fd=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};
g.ed=function(a){a=g.Vc(a);return null===a?null:a.split(".").reverse()};
g.gd=function(a){return a&&"status"in a?a.status:-1};
g.hd=function(a){switch(g.gd(a)){case 200:case 201:case 202:case 203:case 204:case 205:case 206:case 304:return!0;default:return!1}};
yaa=function(a,b,c,d,e,f,k){function l(){4==(n&&"readyState"in n?n.readyState:0)&&b&&yb(b)(n)}
var n=id&&id();if(!("open"in n))return null;"onloadend"in n?n.addEventListener("loadend",l,!1):n.onreadystatechange=l;c=(c||"GET").toUpperCase();d=d||"";n.open(c,a,!0);f&&(n.responseType=f);k&&(n.withCredentials=!0);f="POST"==c;if(e=xaa(a,e))for(var u in e)n.setRequestHeader(u,e[u]),"content-type"==u.toLowerCase()&&(f=!1);f&&n.setRequestHeader("Content-Type","application/x-www-form-urlencoded");n.send(d);return n};
xaa=function(a,b){b=b||{};var c;c||(c=window.location.href);var d=g.Uc(1,a),e=g.Vc(a);d&&e?(d=c,c=a.match(g.Tc),d=d.match(g.Tc),c=c[3]==d[3]&&c[1]==d[1]&&c[4]==d[4]):c=e?g.Vc(c)==e&&(Number(g.Uc(4,c))||null)==(Number(g.Uc(4,a))||null):!0;for(var f in jd){if((e=d=g.v(jd[f]))&&!(e=c)){var e=f,k=g.v("CORS_HEADER_WHITELIST")||{},l=g.Vc(a);e=l?(k=k[l])?g.Ka(k,e):!1:!0}e&&(b[f]=d)}return b};
g.kd=function(a,b){b.method="POST";b.ba||(b.ba={});return g.B(a,b)};
zaa=function(a,b){var c=g.v("XSRF_FIELD_NAME",void 0),d;b.headers&&(d=b.headers["Content-Type"]);return!b.My&&(!g.Vc(a)||b.withCredentials||g.Vc(a)==window.document.location.hostname)&&"POST"==b.method&&(!d||"application/x-www-form-urlencoded"==d)&&!(b.ba&&b.ba[c])};
g.B=function(a,b){var c=b.format||"JSON";b.JU&&(a=window.document.location.protocol+"//"+window.document.location.hostname+(window.document.location.port?":"+window.document.location.port:"")+a);var d=g.v("XSRF_FIELD_NAME",void 0),e=g.v("XSRF_TOKEN",void 0),f=b.ha;f&&(f[d]&&delete f[d],a=g.dd(a,f));var k=b.postBody||"",f=b.ba;zaa(a,b)&&(f||(f={}),f[d]=e);f&&g.ka(k)&&(d=g.cd(k),g.$a(d,f),k=b.xu&&"JSON"==b.xu?JSON.stringify(d):g.ad(d));var l=!1,n,u=yaa(a,function(a){if(!l){l=!0;n&&g.Bb(n);var d=g.hd(a),
e=null;if(d||400<=a.status&&500>a.status)e=Aaa(c,a,b.pb);if(d)a:{switch(c){case "XML":d=0==(0,window.parseInt)(e&&e.return_code,10);break a;case "RAW":d=!0;break a}d=!!e}var e=e||{},f=b.context||g.ea;d?b.X&&b.X.call(f,a,e):b.onError&&b.onError.call(f,a,e);b.Xa&&b.Xa.call(f,a,e)}},b.method,k,b.headers,b.responseType,b.withCredentials);
b.Ac&&0<b.timeout&&(n=g.zb(function(){l||(l=!0,u.abort(),g.Bb(n),b.Ac.call(b.context||g.ea,u))},b.timeout));
return u};
Aaa=function(a,b,c){var d=null;switch(a){case "JSON":a=b.responseText;b=b.getResponseHeader("Content-Type")||"";a&&0<=b.indexOf("json")&&(d=g.Qc(a));break;case "XML":if(b=(b=b.responseXML)?g.ld(b):null)d={},(0,g.y)(b.getElementsByTagName("*"),function(a){d[a.tagName]=g.md(a)})}c&&nd(d);
return d};
nd=function(a){if(g.oa(a))for(var b in a)"html_content"==b||g.ua(b,"_html")?a[b]=g.Ic(g.cc("HTML that is escaped and sanitized server-side and passed through yt.net.ajax"),a[b]):nd(a[b])};
g.ld=function(a){return a?(a=("responseXML"in a?a.responseXML:a).getElementsByTagName("root"))&&0<a.length?a[0]:null:null};
g.md=function(a){var b="";(0,g.y)(a.childNodes,function(a){b+=a.nodeValue});
return b};
g.od=function(){return{apiaryHost:g.v("APIARY_HOST",void 0),cp:g.v("APIARY_HOST_FIRSTPARTY",void 0),gapiHintOverride:g.v("GAPI_HINT_OVERRIDE"),gapiHintParams:g.v("GAPI_HINT_PARAMS",void 0),innertubeApiKey:g.v("INNERTUBE_API_KEY",void 0),innertubeApiVersion:g.v("INNERTUBE_API_VERSION",void 0),DD:g.v("INNERTUBE_CONTEXT_CLIENT_NAME","WEB"),innertubeContextClientVersion:g.v("INNERTUBE_CONTEXT_CLIENT_VERSION",void 0),FD:g.v("INNERTUBE_CONTEXT_HL",void 0),ED:g.v("INNERTUBE_CONTEXT_GL",void 0),vO:g.v("XHR_APIARY_HOST",
void 0)}};
g.pd=function(a){a={client:{hl:a.FD,gl:a.ED,clientName:a.DD,clientVersion:a.innertubeContextClientVersion}};g.v("DELEGATED_SESSION_ID")&&(a.user={onBehalfOfUser:g.v("DELEGATED_SESSION_ID")});return a};
qd=function(){this.A=g.od()};
g.rd=function(a,b,c){this.A=a;this.B=b;this.C=c};
g.wd=function(a,b){g.sd[a.endpoint]=g.sd[a.endpoint]||[];var c=g.sd[a.endpoint];c.push(a.Bb);td[a.endpoint]=b;20<=c.length?g.ud():g.vd()};
g.ud=function(){g.Bb(g.xd);if(!g.Va(g.sd)){for(var a in g.sd){var b=g.yd[a];if(!b){b=td[a];if(!b)continue;b=new b;g.yd[a]=b}var c=b.C();c.requestTimeMs=Math.round((0,g.zd)());c[Baa[a]]=g.sd[a];b.B(a,c,{});delete g.sd[a]}g.Va(g.sd)||g.vd()}};
g.vd=function(){g.Bb(g.xd);g.xd=g.zb(g.ud,g.v("VISIBILITY_TIMEOUT",1E4))};
g.Ad=function(a,b,c,d){var e={};e.eventTimeMs=Math.round(d||(0,g.zd)());e[a]=b;g.wd({endpoint:"log_event",Bb:e},c)};
g.Bd=function(){var a=g.v("client-screen-nonce",void 0);a||(a=g.v("EVENT_ID",void 0));return a};
g.Cd=function(a,b){this.x=g.da(a)?a:0;this.y=g.da(b)?b:0};
g.Dd=function(a,b){this.width=a;this.height=b};
g.C=function(a){return g.ka(a)?window.document.getElementById(a):a};
g.Ed=function(a){return g.ka(a)?window.document.getElementById(a):a};
g.D=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=g.Fd(window.document,"*",a,b)[0];return d||null};
g.Fd=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,k;k=a[f];f++)b==k.nodeName&&(d[e++]=k);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;k=a[f];f++)b=k.className,"function"==typeof b.split&&g.Ka(b.split(/\s+/),c)&&(d[e++]=k);d.length=e;return d}return a};
g.Hd=function(a,b){g.Sa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Gd.hasOwnProperty(d)?a.setAttribute(Gd[d],b):g.ta(d,"aria-")||g.ta(d,"data-")?a.setAttribute(d,b):a[d]=b})};
g.Jd=function(a){return g.Id(a||window)};
g.Id=function(a){a=a.document;a=g.Kd(a)?a.documentElement:a.body;return new g.Dd(a.clientWidth,a.clientHeight)};
g.Md=function(a){var b=g.Ld(a);a=a.parentWindow||a.defaultView;return g.E&&g.Nc("10")&&a.pageYOffset!=b.scrollTop?new g.Cd(b.scrollLeft,b.scrollTop):new g.Cd(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.Ld=function(a){return a.scrollingElement?a.scrollingElement:!g.Nd&&g.Kd(a)?a.documentElement:a.body||a.documentElement};
g.Pd=function(a,b,c){return g.Od(window.document,arguments)};
g.Od=function(a,b){var c=b[0],d=b[1];if(!Caa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',g.xa(d.name),'"');if(d.type){c.push(' type="',g.xa(d.type),'"');var e={};g.$a(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(g.ka(d)?c.className=d:g.ia(d)?c.className=d.join(" "):g.Hd(c,d));2<b.length&&g.Qd(a,c,b,2);return c};
g.Qd=function(a,b,c,d){function e(c){c&&b.appendChild(g.ka(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var f=c[d];!g.ja(f)||g.oa(f)&&0<f.nodeType?e(f):(0,g.y)(Daa(f)?g.Oa(f):f,e)}};
g.Kd=function(a){return"CSS1Compat"==a.compatMode};
g.Rd=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};
g.Sd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};
g.Td=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
Eaa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
Faa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
g.Ud=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
Daa=function(a){if(a&&"number"==typeof a.length){if(g.oa(a))return"function"==typeof a.item||"string"==typeof a.item;if(g.ma(a))return"function"==typeof a.item}return!1};
g.Vd=function(a,b,c,d){c||(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null};
g.Wd=function(a,b,c){a&&(c&&(c=g.ab,c=!(c&&0<=c.toLowerCase().indexOf("cobalt"))),c?a&&(a=g.Pd("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),g.Ud(a).body.appendChild(a)):Gaa(a,b))};
g.Xd=function(a){try{window.navigator&&window.navigator.sendBeacon&&window.navigator.sendBeacon(a,"")||g.Wd(a,void 0)}catch(b){g.Wd(a,void 0)}};
Gaa=function(a,b){var c=new window.Image,d=""+Haa++;Yd[d]=c;c.onload=c.onerror=function(){b&&Yd[d]&&b();delete Yd[d]};
c.src=a};
g.Zd=function(a,b){this.version=a;this.args=b};
g.$d=function(a,b){this.topic=a;this.uf=b};
g.be=function(a,b){var c=g.ae();return c?c.publish.call(c,a.toString(),a,b):!1};
g.ae=function(){return g.p("yt.pubsub2.instance_")};
ce=function(a){g.Zd.call(this,1,arguments)};
ee=function(a){var b=a||window;if(!(b.performance&&b.performance.timing&&b.performance.getEntriesByType))return{Dk:0,Vv:0};a=g.Jd(b);for(var c=[],d=b.document.getElementsByTagName("*"),e=0,f=d.length;e<f;e++){var k=d[e];if("IMG"==k.tagName||"IFRAME"==k.tagName){var l=de(k,k.src,a);if(l){if("IFRAME"==k.tagName){var n;try{n=ee(k.contentWindow).Dk}catch(u){n=0}0<n&&(l.timing=n)}c.push(l)}}(l=b.getComputedStyle(k)["background-image"])&&(l=Iaa.exec(l))&&1<l.length&&(l=de(k,l[1],a))&&c.push(l)}n=b.performance.getEntriesByType("resource");
k=b.performance.getEntriesByType("mark");d={};e=0;for(f=n.length;e<f;e++)l=n[e],d[l.name]=l.responseEnd;e=0;for(f=k.length;e<f;e++)l=k[e],"mark_iframe_loaded: "==l.name.slice(0,20)&&(d[l.name.slice(20)]=l.startTime);e=0;for(f=c.length;e<f;e++)k=c[e],k.timing||(k.timing=d[k.url]||0);b=Jaa(b,n);a=Kaa(b,a,c);k=c=0;if(a.length)for(d=n=0,e=a.length;d<e;d++)f=a[d],k=f.timing-k,0<k&&1>n&&(c+=(1-n)*k),k=f.timing,n=f.progress;return{Dk:Math.round(c||b),Vv:k}};
de=function(a,b,c){if(b&&a.getBoundingClientRect){var d=a.getBoundingClientRect();a=Math.max(d.top,0);var e=Math.min(d.right,c.width);c=Math.min(d.bottom,c.height);d=Math.max(d.left,0);if(c>a&&e>d)return new Laa(a,e,c,d,b)}return null};
Jaa=function(a,b){var c,d=a.performance.timing.navigationStart;if("msFirstPaint"in a.performance.timing)c=a.performance.timing.A-d;else if("chrome"in a&&"loadTimes"in a.chrome){var e=a.chrome.loadTimes(),f=e.firstPaintTime;if(0<f){var k=e.startLoadTime;"requestTime"in e&&(k=e.requestTime);f>=k&&(c=1E3*(f-k))}}if(void 0===c||0>c||12E4<c){c=a.performance.timing.responseStart-d;for(var l={},d=a.document.getElementsByTagName("head")[0].children,e=0,f=d.length;e<f;e++)k=d[e],"SCRIPT"==k.tagName&&k.src&&
!k.async?l[k.src]=!0:"LINK"==k.tagName&&"stylesheet"==k.rel&&k.href&&(l[k.href]=!0);b.some(function(a){if(!l[a.name]||"script"!=a.initiatorType&&"link"!=a.initiatorType)return!0;a=a.responseEnd;if(void 0===c||a>c)c=a})}return Math.max(c,0)||0};
Kaa=function(a,b,c){for(var d={0:0},e=0,f=0,k=c.length;f<k;f++){var l=c[f],n=a;l.timing>a&&(n=l.timing);d[n]||(d[n]=0);l=(l.A-l.D)*(l.B-l.C);d[n]+=l;e+=l}f=b.width*b.height;0<f&&(f=.1*Math.max(f-e,0),a in d||(d[a]=0),d[a]+=f,e+=f);a=[];if(e){for(var u in d)b=new Maa((0,window.parseFloat)(u),d[u]),a.push(b);a.sort(function(a,b){return a.timing-b.timing});
f=d=0;for(k=a.length;f<k;f++)b=a[f],d+=b.ul,b.progress=d/e}return a};
Laa=function(a,b,c,d,e){this.A=c;this.C=d;this.B=b;this.D=a;this.url=e};
Maa=function(a,b){this.ul=b;this.timing=a};
Naa=function(){if("cold"==fe().yt_lt){var a=ge(),b=he(),c;for(c in a)"tick_"+c in b||ie(c,a[c]);a=fe();for(c in a)"info_"+c in b||je(c,a[c])}};
g.me=function(a,b,c){b||"_"==a[0]||ke(a);ge(c)[a]=b||(0,g.zd)();ie(a,b,c)||le(!1,c)};
ie=function(a,b,c){he(c)["tick_"+a]=b;return g.Hc("csi_on_gel")?(c=ne(c),"_start"==a?g.Ad("latencyActionBaselined",{clientActionNonce:c},qd,b):g.Ad("latencyActionTicked",{tickName:a,clientActionNonce:c},qd,b),!0):!1};
pe=function(a,b){oe("yt_sts",a,void 0);g.me("_start",b,void 0)};
oe=function(a,b,c){fe(c)[a]=b;je(a,b,c)};
je=function(a,b,c){he(c)["info_"+a]=b;if(g.Hc("csi_on_gel"))if(a in qe){var d={};a=qe[a];a in Oaa&&(b=!!b);d[a]=b;b=ne(c);d.clientActionNonce=b;g.Ad("latencyActionInfo",d,qd)}else g.Db(Error("Unknown label "+a+" logged with GEL CSI."))};
Qaa=function(){var a=g.v("TIMING_INFO",{}),b;for(b in a)oe(b,a[b]);(a=g.Bd())&&oe("csn",a);(a=g.v("PREVIOUS_ACTION",void 0))&&oe("pa",a);a=fe();a.p=g.v("CLIENT_PROTOCOL")||"unknown";a.t=g.v("CLIENT_TRANSPORT")||"unknown";re.now&&re.timing?(a=re.timing.navigationStart+re.now(),a=Math.round((0,g.F)()-a)):a=null;null!=a&&oe("yt_hrd",a);window.navigator&&window.navigator.sendBeacon&&oe("ba",1);if("cold"==fe().yt_lt){a=re.timing||{};a:if(a.msFirstPaint)b=Math.max(0,a.msFirstPaint);else{if(b=window.chrome)if(b=
b.loadTimes,g.ma(b)){b=b();var c=1E3*Math.min(b.requestTime||window.Infinity,b.startLoadTime||window.Infinity),c=window.Infinity===c?0:a.navigationStart-c;b=Math.max(0,Math.round(1E3*b.firstPaintTime+c)||0);break a}b=0}0<b&&g.me("fpt",b);b=se(void 0).span;te(a,b);re.getEntriesByType&&Paa();a=g.v("SPEEDINDEX_FOR_ACTIONS",void 0);b=g.v("TIMING_ACTION",void 0);a&&-1<a.indexOf(b)&&(a=(0,g.zd)(),b=ee(),c=(0,g.zd)(),0<b.Dk&&(oe("si",b.Dk),g.me("vsc",ue(b.Vv)),g.me("sics",a),g.me("sice",c)));a=[];if(window.document.querySelector&&
re&&re.getEntriesByName)for(var d in ve)if(b=window.document.querySelector(d)){var c="",e=b.nodeName;"SCRIPT"==e?c=b.src:"LINK"==e&&(c=b.href);c&&(b=re.getEntriesByName(c))&&b[0]&&a.push(ve[d]+"."+Math.round(b[0].duration))}a.length&&oe("rs",a.join(","))}};
we=function(a){a=ge(a);if(a.aft)return a.aft;for(var b=g.v("TIMING_AFT_KEYS",["ol"]),c=b.length,d=0;d<c;d++){var e=a[b[d]];if(e)return e}return window.NaN};
te=function(a,b){var c=b||se(void 0).span,d;d=a.redirectEnd-a.redirectStart;0<d&&(c.rtime_=d);d=a.domainLookupEnd-a.domainLookupStart;0<d&&(c.dns_=d);d=a.connectEnd-a.connectStart;0<d&&(c.tcp_=d);d=a.connectEnd-a.secureConnectionStart;a.secureConnectionStart>=a.navigationStart&&0<d&&(c.stcp_=d);d=a.responseStart-a.requestStart;0<d&&(c.req_=d);d=a.responseEnd-a.responseStart;0<d&&(c.rcv_=d)};
ue=function(a){return Math.round(re.timing.navigationStart+a)};
Paa=function(){var a=window.location.protocol,b=re.getEntriesByType("resource"),c=b.filter(function(b){return 0==b.name.indexOf(a+"//fonts.googleapis.com/css?family=")})[0],b=b.filter(function(b){return 0==b.name.indexOf(a+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});
c&&0<c.startTime&&0<c.responseEnd&&(g.me("wfcs",ue(c.startTime)),g.me("wfce",ue(c.responseEnd)));b&&0<b.startTime&&0<b.responseEnd&&(g.me("wffs",ue(b.startTime)),g.me("wffe",ue(b.responseEnd)))};
Ce=function(a){var b=ge(a),c=se(a).span,d=fe(a),e=g.p("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))xe(e),ye(a),ze(),Ae(!1)}else{var f=g.v("CSI_SERVICE_NAME","youtube"),e={v:2,s:f,action:g.v("TIMING_ACTION",void 0)},k=d.srt;delete d.srt;void 0===b.srt&&(k||0===k||(k=re.timing||{},k=Math.max(0,k.responseStart-k.navigationStart),(0,window.isNaN)(k)&&d.pt&&(k=d.pt)),k||0===k)&&(d.srt=Math.round(k));if(d.h5jse){var l=window.location.protocol+g.p("ytplayer.config.assets.js");(l=re.getEntriesByName?
re.getEntriesByName(l)[0]:null)?d.h5jse=Math.round(d.h5jse-l.responseEnd):delete d.h5jse}b.aft=we(a);var l=b._start,n=ge(a),u=n.pbr,w=n.vc,n=n.pbs;u&&w&&n&&u<w&&w<n&&1==fe(a).yt_vis&&"youtube"==f&&(oe("yt_lt","hot_bg",a),f=b.vc,u=b.pbs,delete b.aft,d.aft=Math.round(u-f));for(var H in d)"_"!=H.charAt(0)&&(e[H]=d[H]);b.ps=(0,g.zd)();d={};H=[];for(var L in b)"_"!=L.charAt(0)&&(f=Math.round(b[L]-l),g.Hc("enable_negative_ticks")||(f=Math.max(f,0)),d[L]=f,H.push(L+"."+f));e.rt=H.join(",");b=e;L=[];for(var aa in c)"_"!=
aa.charAt(0)&&L.push(aa+"."+Math.round(c[aa]));b.it=L.join(",");(aa=g.p("ytdebug.logTiming"))&&aa(e,d,c);g.Hc("navigation_only_csi_reset")||(ye(a),ze(),Ae(!1));g.v("EXP_DEFER_CSI_PING")?(Be(),g.m("yt.timing.deferredPingArgs_",e,void 0),a=g.zb(Be,0),g.m("yt.timing.deferredPingTimer_",a,void 0)):xe(e);g.be(Raa,new ce(d.aft+(k||0)))}};
le=function(a,b){if(!g.Hc("navigation_only_csi_reset")||!g.p("yt.timing.pingSent_")||b){var c=g.v("TIMING_ACTION",void 0),d=ge(b);if(g.p("yt.timing.ready_")&&c&&d._start&&we(b)){var c=!0,e=g.v("TIMING_WAIT",[]);if(!a&&e.length)for(var f=0,k=e.length;f<k;++f)if(!(e[f]in d)){c=!1;break}(c||b)&&Ce(b)}}};
xe=function(a){if(g.v("DEBUG_CSI_DATA")){var b=g.p("yt.timing.csiData");b||(b=[],g.m("yt.timing.csiData",b,void 0));b.push({page:window.location.href,time:new Date,args:a})}g.v("EXP_DEFER_CSI_PING")&&(g.Bb(g.p("yt.timing.deferredPingTimer_")),g.m("yt.timing.deferredPingArgs_",null,void 0));var b="",c;for(c in a)b+="&"+c+"="+a[c];a="/csi_204?"+b.substring(1);window.navigator&&window.navigator.sendBeacon?g.Xd(a):g.Wd(a);Ae(!0)};
Be=function(a){if(g.v("EXP_DEFER_CSI_PING")){var b=g.p("yt.timing.deferredPingArgs_");b&&(a&&(b.yt_fss=a),xe(b))}};
ne=function(a){var b=se(a).nonce;if(!b){var c;a:{if(window.crypto&&window.crypto.getRandomValues)try{var d=Array(16),e=new window.Uint8Array(16);window.crypto.getRandomValues(e);for(b=0;b<d.length;b++)d[b]=e[b];c=d;break a}catch(f){}c=Array(16);for(d=0;16>d;d++){e=(0,g.F)();for(b=0;b<e%23;b++)c[d]=Math.random();c[d]=Math.floor(256*Math.random())}if(De)for(d=1,e=0;e<De.length;e++)c[d%16]=c[d%16]^c[(d-1)%16]/4^De.charCodeAt(e),d++}d=[];for(e=0;e<c.length;e++)d.push("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_".charAt(c[e]&
63));b=d.join("");se(a).nonce=b}return b};
ge=function(a){return se(a).tick};
fe=function(a){return se(a).info};
he=function(a){a=se(a);"gel"in a||(a.gel={});return a.gel};
se=function(a){return g.p("ytcsi."+(a||"")+"data_")||ye(a)};
ye=function(a){var b={tick:{},span:{},info:{}};g.m("ytcsi."+(a||"")+"data_",b,void 0);return b};
Ae=function(a){g.m("yt.timing.pingSent_",a,void 0)};
Ee=function(a){if(!g.p("yt.timing.pingSent_")){if(!g.Hc("send_empty_timing")){var b=g.v("CSI_SERVICE_NAME","youtube");if(!g.v("TIMING_ACTION",void 0)||!b)return}g.me("aa");oe("ap",1);oe("yt_fss",a);Ce()}};
g.Fe=function(a,b){g.Wd("/gen_204?"+a,b)};
g.Ge=function(a){if(a.classList)return a.classList;a=a.className;return g.ka(a)&&a.match(/\S+/g)||[]};
g.G=function(a,b){return a.classList?a.classList.contains(b):g.Ka(g.Ge(a),b)};
g.I=function(a,b){a.classList?a.classList.add(b):g.G(a,b)||(a.className+=0<a.className.length?" "+b:b)};
g.J=function(a,b){a.classList?a.classList.remove(b):g.G(a,b)&&(a.className=(0,g.He)(g.Ge(a),function(a){return a!=b}).join(" "))};
g.Ie=function(a,b,c){c?g.I(a,b):g.J(a,b)};
g.Ke=function(a){var b=a.__yt_uid_key;b||(b=Je(),a.__yt_uid_key=b);return b};
g.Le=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,g.y)(a.childNodes,function(a){b.appendChild(g.Le(a))}):b.innerHTML=a.innerHTML;
return b};
g.Me=function(a){this.type="";this.state=this.source=this.data=this.currentTarget=this.relatedTarget=this.target=null;this.charCode=this.keyCode=0;this.shiftKey=this.ctrlKey=this.altKey=!1;this.rotation=this.clientY=this.clientX=0;this.scale=1;this.changedTouches=this.touches=null;if(a=a||window.event){this.event=a;for(var b in a)b in Saa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=
b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;this.hn=a.pageX;this.jn=a.pageY}};
g.Oe=function(a,b,c,d){a.addEventListener&&("mouseenter"!=b||"onmouseenter"in window.document?"mouseleave"!=b||"onmouseenter"in window.document?"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"):b="mouseout":b="mouseover");return g.Ua(g.Ne,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
g.K=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=g.Oe(a,b,c,d);if(e)return e;var e=++Pe.count+"",f=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),k;k=f?function(d){d=new g.Me(d);if(!g.Vd(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new g.Me(b);
b.currentTarget=a;return c.call(a,b)};
k=yb(k);a.addEventListener?("mouseenter"==b&&f?b="mouseover":"mouseleave"==b&&f?b="mouseout":"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"),a.addEventListener(b,k,d)):a.attachEvent("on"+b,k);g.Ne[e]=[a,b,c,k,d];return e};
g.M=function(a){a&&("string"==typeof a&&(a=[a]),(0,g.y)(a,function(a){if(a in g.Ne){var c=g.Ne[a],d=c[0],e=c[1],f=c[3],c=c[4];d.removeEventListener?d.removeEventListener(e,f,c):d.detachEvent&&d.detachEvent("on"+e,f);delete g.Ne[a]}}))};
g.Qe=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};
g.Se=function(){if(null==g.p("_lact",window)){var a=(0,window.parseInt)(g.v("LACT"),10),a=(0,window.isFinite)(a)?(0,g.F)()-Math.max(a,0):-1;g.m("_lact",a,window);-1==a&&Re();g.K(window.document,"keydown",Re);g.K(window.document,"keyup",Re);g.K(window.document,"mousedown",Re);g.K(window.document,"mouseup",Re);g.x("page-mouse",Re);g.x("page-scroll",Re);g.x("page-resize",Re)}};
Re=function(){null==g.p("_lact",window)&&(g.Se(),g.p("_lact",window));var a=(0,g.F)();g.m("_lact",a,window);g.z("USER_ACTIVE")};
g.Te=function(){var a=g.p("_lact",window);return null==a?-1:Math.max((0,g.F)()-a,0)};
Ue=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||g.Ya(Taa);this.assets=a.assets||{};this.attrs=a.attrs||g.Ya(Uaa);this.params=a.params||g.Ya(Vaa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
g.Ve=function(a){a instanceof Ue||(a=new Ue(a));return a};
Xe=function(){return null!=g.We};
g.Ye=function(){return g.We?g.We.invoke():null};
Ze=function(){return(0,window.parseInt)(g.v("DCLKSTAT",0),10)};
g.$e=function(a){this.A=a||{cookie:""}};
g.bf=function(a){a=(a.A.cookie||"").split(g.af);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
g.df=function(a,b,c,d){g.cf.set(""+a,b,c,"/",d||"youtube.com")};
g.gf=function(a,b,c){var d=g.v("VALID_SESSION_TEMPDATA_DOMAINS",[]),e=g.Vc(window.location.href);e&&d.push(e);e=g.Vc(a);if(g.Ka(d,e)||!e&&g.ta(a,"/"))if(a=g.Wc(a),a=g.Xc(a))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&(ef(a,b,c),ff(b))):(ef(a,b),ff(b))};
ef=function(a,b,c){var d=g.v("ST_BASE36",!0),e;e=g.v("ST_SHORT",!0)?"ST-":"s_tempdata-";a=e=d?e+g.Ea(a).toString(36):e+g.Ea(a);c=c||5;b=b?g.ad(b):"";g.df(a,b,c)};
ff=function(a){if(a){a=a.itct||a.ved;var b=g.p("yt.logging.screenreporter.storeParentElement");a&&b&&b(new g.rd(a))}};
g.hf=function(a,b,c){c=c||"";g.Ac(window.location,g.bd(a,b||{})+c)};
g.jf=function(a,b){b&&g.gf(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):g.hf(a)};
g.kf=function(a,b,c){var d=g.v("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&g.gf(a,b);if(c)return!1;g.jf(a);return!0};
g.nf=function(){return g.Nd?"Webkit":g.lf?"Moz":g.E?"ms":g.mf?"O":null};
g.of=function(){return g.Nd?"-webkit":g.lf?"-moz":g.E?"-ms":g.mf?"-o":null};
g.pf=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
g.qf=function(a,b){return a&&b?b instanceof g.pf?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
g.rf=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};
g.tf=function(a,b){var c=sf[b];if(!c){var d=Fa(b),c=d;void 0===a.style[d]&&(d=g.nf()+g.Ga(d),void 0!==a.style[d]&&(c=d));sf[b]=c}return c};
g.uf=function(a,b){var c=a.style[Fa(b)];return"undefined"!==typeof c?c:a.style[g.tf(a,b)]||""};
g.vf=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};
g.wf=function(a,b){a.style.height=g.vf(b,!0)};
g.xf=function(a,b){a.style.width=g.vf(b,!0)};
g.yf=function(a,b){a.style.display=b?"":"none"};
g.Af=function(){var a=g.cf.get("PREF",void 0);if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(g.zf[d]=c.toString())}};
Bf=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};
Cf=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};
g.Df=function(a){a=void 0!==g.zf[a]?g.zf[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};
g.Ef=function(a,b){return!!((g.Df("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
g.Ff=function(a,b){(a=g.C(a))&&a.style&&(g.yf(a,b),g.Ie(a,"hid",!b))};
g.Gf=function(a){return(a=g.C(a))?!("none"==a.style.display||g.G(a,"hid")):!1};
Waa=function(a){if(a=g.C(a))g.Gf(a)?(g.yf(a,!1),g.I(a,"hid")):(g.yf(a,!0),g.J(a,"hid"))};
g.N=function(a){(0,g.y)(arguments,function(a){!g.ja(a)||a instanceof window.Element?g.Ff(a,!0):(0,g.y)(a,function(a){g.N(a)})})};
g.O=function(a){(0,g.y)(arguments,function(a){!g.ja(a)||a instanceof window.Element?g.Ff(a,!1):(0,g.y)(a,function(a){g.O(a)})})};
g.Hf=function(a){(0,g.y)(arguments,function(a){g.ja(a)?(0,g.y)(a,function(a){g.Hf(a)}):Waa(a)})};
g.Jf=function(){this.A=this.minor=this.major=0;this.C="";var a=g.p("window.navigator.plugins"),b=g.p("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,f=c.length;e<f;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.C=b;b=a;this.major=b[0];this.minor=b[1];this.A=b[2];if(0>=this.major){var k,l,n,u;if(g.If)try{k=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(w){k=null}else n=window.document.body,u=window.document.createElement("object"),u.setAttribute("type","application/x-shockwave-flash"),k=n.appendChild(u);if(k&&"GetVariable"in k)try{l=k.GetVariable("$version")}catch(w){l=""}n&&u&&n.removeChild(u);(k=l||
"")?(k=k.split(" ")[1].split(","),k=[(0,window.parseInt)(k[0],10)||0,(0,window.parseInt)(k[1],10)||0,(0,window.parseInt)(k[2],10)||0]):k=[0,0,0];this.major=k[0];this.minor=k[1];this.A=k[2]}};
Kf=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.major>b[0]||a.major==b[0]&&a.minor>b[1]||a.major==b[0]&&a.minor==b[1]&&a.A>=b[2]};
Lf=function(a){return-1<a.C.indexOf("Gnash")&&-1==a.C.indexOf("AVM2")||9==a.major&&1==a.minor||9==a.major&&0==a.minor&&1==a.A?!1:9<=a.major};
Xaa=function(a){return g.Mf?!Kf(a,11,2):g.Nf?!Kf(a,11,3):!Lf(a)};
Of=function(a,b,c){if(b){a=g.ka(a)?g.Ed(a):a;var d=g.Ya(c.attrs);d.tabindex=0;var e=g.Ya(c.params);e.flashvars=g.ad(c.args);if(g.If){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var f in d)b.setAttribute(f,d[f]);for(f in e)d=window.document.createElement("param"),d.setAttribute("name",f),d.setAttribute("value",e[f]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");b.setAttribute("name",
d.id);for(f in d)b.setAttribute(f,d[f]);for(f in e)b.setAttribute(f,e[f])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};
g.Rf=function(a,b){a=g.ka(a)?g.Ed(a):a;b=g.Ve(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=g.Jf.getInstance();Kf(c,b.minVersion)?(c=Pf(b,c),Of(a,c,b)):Qf(a,b,c)};
Sf=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=g.Ve(a);var d=!!b,e=g.C(a.attrs.id),f=e?e.parentNode:null;if(e&&f){if(window!=window.top){var k=null;if(window.document.referrer){var l=window.document.referrer.substring(0,128);waa(l)||(k=l)}else k="unknown";k&&(d=!0,a.args.framer=k)}k=g.Jf.getInstance();if(Kf(k,a.minVersion)){var l=Pf(a,k),n="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(n=e.getAttribute("src")||e.movie);(n!=l||d)&&Of(f,l,a);Xaa(k)&&Yaa()}else Qf(f,a,k);c&&c()}else g.zb(function(){Sf(a,
b,c)},50)}};
Qf=function(a,b,c){0==c.major&&b.fallback?b.fallback():0==c.major&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+g.Gb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};
Pf=function(a,b){var c;(c=Lf(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Kf(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.url};
Yaa=function(){var a=g.C("flash10-promo-div"),b=g.Ef(g.Af.getInstance(),107);a&&!b&&g.N(a)};
g.Tf=function(a,b){var c=a.match(Zaa);window.spf.style.load(a,c?c[1]:"",b)};
g.Uf=function(a){g.qb.call(this);this.A=[];this.C=a||this};
Vf=function(a,b,c,d){d=yb((0,g.q)(d,a.C));b.addEventListener(c,d);a.A.push({target:b,name:c,Ub:d})};
Wf=function(a){for(;a.A.length;){var b=a.A.pop();b.target.removeEventListener(b.name,b.Ub)}};
Zf=function(a,b){g.qb.call(this);this.O=this.D=a;this.ia=b;this.L=!1;this.api={};this.Qa=this.U=null;this.Y=new g.ub;g.tb(this,this.Y);this.B={};this.F=this.Wa=this.C=this.kb=this.A=null;this.aa=!1;this.W=this.G=this.M=this.R=null;this.Ya={};this.fc=["onReady"];this.ea=new g.Uf(this);g.tb(this,this.ea);this.rb=null;this.Db=window.NaN;this.ga={};Xf(this);this.fe("onDetailedError",(0,g.q)(this.BI,this));this.fe("onTabOrderChange",(0,g.q)(this.ey,this));this.fe("onTabAnnounce",(0,g.q)(this.Uo,this));
this.fe("WATCH_LATER_VIDEO_ADDED",(0,g.q)(this.EI,this));this.fe("WATCH_LATER_VIDEO_REMOVED",(0,g.q)(this.FI,this));g.Yf||(this.fe("onMouseWheelCapture",(0,g.q)(this.lI,this)),this.fe("onMouseWheelRelease",(0,g.q)(this.mI,this)));this.fe("onAdAnnounce",(0,g.q)(this.Uo,this));this.H=new g.Uf(this);g.tb(this,this.H);this.gb=!1;this.ab=null};
ag=function(a,b){a.kb=b;a.A=b.clone();a.C=a.A.attrs.id||a.C;"video-player"==a.C&&(a.C=a.ia,a.A.attrs.id=a.ia);a.O.id==a.C&&(a.C+="-player",a.A.attrs.id=a.C);a.A.args.enablejsapi="1";a.A.args.playerapiid=a.ia;a.Wa||(a.Wa=$f(a,a.A.args.jsapicallback||"onYouTubePlayerReady"));a.A.args.jsapicallback=null;var c=a.A.attrs.width;c&&g.xf(a.O,Number(c)||c);(c=a.A.attrs.height)&&g.wf(a.O,Number(c)||c)};
bg=function(a){a.A.loaded||(a.A.loaded=!0,"0"!=a.A.args.autoplay?a.api.loadVideoByPlayerVars(a.A.args):a.api.cueVideoByPlayerVars(a.A.args))};
cg=function(a){if(!g.da(a.A.disable.flash)){var b=a.A.disable,c;c=Kf(g.Jf.getInstance(),a.A.minVersion);b.flash=!c}return!a.A.disable.flash};
fg=function(a,b){if((!b||(5!=($aa[b.errorCode]||5)?0:-1!=aba.indexOf(b.errorCode)))&&cg(a)){var c=dg(a);c&&c.stopVideo&&c.stopVideo();var d=a.A;c&&c.getUpdatedConfigurationData&&(c=c.getUpdatedConfigurationData(),d=g.Ve(c));d.args.autoplay=1;d.args.html5_unavailable="1";ag(a,d);eg(a,"flash")}};
eg=function(a,b){if(!a.isDisposed()){if(!b){var c;if(!(c=!a.A.html5&&cg(a))){if(!g.da(a.A.disable.html5)){var d;c=!0;void 0!=a.A.args.deviceHasDisplay&&(c=a.A.args.deviceHasDisplay);if(2.2==gg)d=!0;else{a:{var e=c;c=g.p("yt.player.utils.videoElement_");c||(c=window.document.createElement("video"),g.m("yt.player.utils.videoElement_",c,void 0));try{if(c.canPlayType)for(var e=e?bba:cba,f=0;f<e.length;f++)if(c.canPlayType(e[f])){d=null;break a}d="fmt.noneavailable"}catch(k){d="html5.missingapi"}}d=!d}d&&
(d=hg(a)||a.A.assets.js);a.A.disable.html5=!d;d||(a.A.args.html5_unavailable="1")}c=!!a.A.disable.html5}b=c?cg(a)?"flash":"unsupported":"html5"}("flash"==b?a.sO:"html5"==b?a.tO:a.uO).call(a)}};
hg=function(a){var b=!0,c=dg(a);c&&a.A&&(a=a.A,b=g.A(c,"version")==a.assets.js);return b&&!!g.p("yt.player.Application.create")};
dg=function(a){var b=g.C(a.C);!b&&a.O&&a.O.querySelector&&(b=a.O.querySelector("#"+a.C));return b};
ig=function(a,b,c){var d=b[c];return function(){try{return a.rb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.rb=e,g.Db(e,"WARNING"))}}};
Xf=function(a){a.L=!1;if(a.Qa)for(var b in a.B)a.Qa(b,a.B[b]);for(var c in a.ga)g.Bb((0,window.parseInt)(c,10));a.ga={};a.U=null;a.Qa=null;for(var d in a.api)a.api[d]=null;a.api.addEventListener=(0,g.q)(a.fe,a);a.api.removeEventListener=(0,g.q)(a.zM,a);a.api.destroy=(0,g.q)(a.dispose,a);a.api.getLastError=(0,g.q)(a.Dz,a);a.api.getPlayerType=(0,g.q)(a.Tz,a);a.api.getCurrentVideoConfig=(0,g.q)(a.az,a);a.api.loadNewVideoConfig=(0,g.q)(a.vo,a);a.api.isReady=(0,g.q)(a.IO,a)};
$f=function(a,b){var c=b;if("string"==typeof b){if(a.Ya[b])return a.Ya[b];c=function(){var a=g.p(b);a&&a.apply(g.ea,arguments)};
a.Ya[b]=c}return c?c:null};
dba=function(a,b){var c="ytPlayer"+b+a.ia;a.B[b]=c;g.ea[c]=function(c){var e=g.zb(function(){a.isDisposed()||(a.Y.oa(b,c),g.Wa(a.ga,String(e)))},0);
g.Xa(a.ga,String(e),!0)};
return c};
jg=function(a){return(a=dg(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
kg=function(a){g.me("dcp");a.cancel();Xf(a);a.F=null;a.A&&(a.A.loaded=!1);var b=dg(a);"html5"==jg(a)?a.M=b:b&&b.destroy&&b.destroy();g.Rd(a.D);Wf(a.ea);a.G=null;a.W=null};
g.ng=function(a,b){a=g.ka(a)?g.Ed(a):a;b=g.Ve(b);var c=g.lg+"_"+g.qa(a),d=g.mg[c];if(d)return d.vo(b),d.api;d=new Zf(a,c);g.mg[c]=d;g.z("player-added",d.api);g.rb(d,g.r(eba,d));g.zb(function(){d.vo(b)},0);
return d.api};
eba=function(a){g.mg[a.getId()]=null};
g.og=function(a){a=g.C(a);if(!a)return null;var b=g.lg+"_"+g.qa(a),c=g.mg[b];c||(c=new Zf(a,b),g.mg[b]=c);return c.api};
g.pg=function(){return g.G(g.C("page-container"),"remote-connected")};
fba=function(){g.m("yt.abuse.botguardInitialized",Xe,void 0);g.m("yt.abuse.invokeBotguard",g.Ye,void 0);g.m("yt.abuse.dclkstatus.checkDclkStatus",Ze,void 0);g.m("yt.player.exports.navigate",g.kf,void 0);g.m("yt.player.embed",g.ng,void 0);g.m("yt.player.getPlayerByElement",g.og,void 0);g.m("yt.util.activity.init",g.Se,void 0);g.m("yt.util.activity.getTimeSinceActive",g.Te,void 0);g.m("yt.util.activity.setTimestamp",Re,void 0);var a=g.p("ytplayer.config");qg(a);g.p("ytspf.enabled")&&(rg=g.Ab(sg,5E3),
(a=g.tg())?(a.addEventListener("onReady",sg),a.addEventListener("onStateChange",sg)):ug("unable to init PP monitor"))};
qg=function(a){for(var b in g.mg){var c=g.mg[b];c&&c.cancel()}if(a=a||null){b=g.tg();var d=!0,c=g.vg;g.vg=null;b&&b.getVideoData&&c&&(d=b.getVideoData(),d=!!c.fullscreen||d.video_id!=a.args.video_id||d.list!=a.args.list||d.video_id!=c.videoId||d.list!=c.listId);d?(wg="",g.ng("player-api",a)):b.playVideo();a=g.Ve(a);a.loaded=!0}sg();g.m("ytplayer.config",a,void 0)};
g.tg=function(){var a=g.p("yt.player.getPlayerByElement");return a?a("player-api"):null};
sg=function(){var a=g.tg();if(a){var b;b=g.C("player");b=!b||g.G(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==g.v("PAGE_NAME"),e=g.pg();!c||d||e||(ug("PP playing off watch (paused)"),a.pauseVideo());b&&d?ug("PP off-screen on watch"):b||d||ug("PP !off-screen off watch")}};
ug=function(a){var b=g.v("PAGE_NAME");b&&(b=[b,wg,g.p("_spf_state.nav-counter")],a+="("+b.join(",")+")",g.m("yt.www.persistentplayer.issue",a,void 0),g.Db(Error(a),"WARNING"))};
g.xg=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};
g.yg=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};
g.Ag=function(a,b){this.A=0;this.L=void 0;this.D=this.C=this.B=null;this.F=this.G=!1;if(a!=g.fa)try{var c=this;a.call(b,function(a){g.zg(c,2,a)},function(a){g.zg(c,3,a)})}catch(d){g.zg(this,3,d)}};
Bg=function(){this.next=this.context=this.C=this.D=this.A=null;this.B=!1};
g.Dg=function(a,b,c){var d=Cg.get();d.D=a;d.C=b;d.context=c;return d};
gba=function(a,b,c){Eg(a,b,c,null)||nb(g.r(b,a))};
g.Fg=function(a){return new g.Ag(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},k=function(a){c(a)},l=0,n;l<a.length;l++)n=a[l],gba(n,g.r(f,l),k);
else b(e)})};
Gg=function(a,b){if(0==a.A)if(a.B){var c=a.B;if(c.C){for(var d=0,e=null,f=null,k=c.C;k&&(k.B||(d++,k.A==a&&(e=k),!(e&&1<d)));k=k.next)e||(f=k);e&&(0==c.A&&1==d?Gg(c,b):(f?(d=f,d.next==c.D&&(c.D=d),d.next=d.next.next):Hg(c),Ig(c,e,3,b)))}a.B=null}else g.zg(a,3,b)};
g.Kg=function(a,b){a.C||2!=a.A&&3!=a.A||Jg(a);a.D?a.D.next=b:a.C=b;a.D=b};
g.Mg=function(a,b,c,d){var e=g.Dg(null,null,null);e.A=new g.Ag(function(a,k){e.D=b?function(c){try{var e=b.call(d,c);a(e)}catch(u){k(u)}}:a;
e.C=c?function(b){try{var e=c.call(d,b);!g.da(e)&&b instanceof Lg?k(b):a(e)}catch(u){k(u)}}:k});
e.A.B=a;g.Kg(a,e);return e.A};
g.zg=function(a,b,c){0==a.A&&(a==c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.A=1,Eg(c,a.W,a.H,a)||(a.L=c,a.A=b,a.B=null,Jg(a),3!=b||c instanceof Lg||hba(a,c)))};
Eg=function(a,b,c,d){if(a instanceof g.Ag)return g.Kg(a,g.Dg(b||g.fa,c||null,d)),!0;if(g.yg(a))return a.then(b,c,d),!0;if(g.oa(a))try{var e=a.then;if(g.ma(e))return iba(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1};
iba=function(a,b,c,d,e){function f(a){l||(l=!0,d.call(e,a))}
function k(a){l||(l=!0,c.call(e,a))}
var l=!1;try{b.call(a,k,f)}catch(n){f(n)}};
Jg=function(a){a.G||(a.G=!0,nb(a.O,a))};
Hg=function(a){var b=null;a.C&&(b=a.C,a.C=b.next,b.next=null);a.C||(a.D=null);return b};
Ig=function(a,b,c,d){if(3==c&&b.C&&!b.B)for(;a&&a.F;a=a.B)a.F=!1;if(b.A)b.A.B=null,Ng(b,c,d);else try{b.B?b.D.call(b.context):Ng(b,c,d)}catch(e){Og.call(null,e)}gb(Cg,b)};
Ng=function(a,b,c){2==b?a.D.call(a.context,c):a.C&&a.C.call(a.context,c)};
hba=function(a,b){a.F=!0;nb(function(){a.F&&Og.call(null,b)})};
Lg=function(a){g.sa.call(this,a)};
lba=function(){var a=g.Jd(),b=new g.rf(0,0,a.width,a.height);oe("vps",a.width+"."+a.height);g.me("vpc");for(var a=window.document.querySelectorAll(".yt-lockup-thumbnail img[data-ytimg]"),c=a.length,d=[],e=!0,f=[],k=0;k<c;k++){var l=a[k],n;a:{n=b;for(var u=l,w=window.document.body;u!=w;){var H=g.Ke(u);if(H in Pg)break;var L=window.getComputedStyle(u);if("none"==L.display||"hidden"==L.visibility){n=!1;break a}L=u.getBoundingClientRect();L=new g.rf(L.top,L.left,L.width,L.height);if(!(n.left<=L.left+
L.width&&L.left<=n.left+n.width&&n.top<=L.top+L.height&&L.top<=n.top+n.height)){n=!1;break a}Pg[H]=!0;u=u.parentElement}n=!0}n&&(f.push(l),d.push(jba(l)),l.loadTime||(e=!1))}e&&oe("yt_eil",1);g.me("vpcc");return g.Fg(d).then(kba)};
kba=function(a){return Math.max(Math.max.apply(null,a),0)};
jba=function(a){return new g.Ag(function(b){if(a.loadTime)b((0,window.parseInt)(a.loadTime,10));else{var c=g.K(a,"load",function(){if(a.loadTime){var d=(0,window.parseInt)(a.loadTime,10);g.M(c);b(d)}});
Qg.push(c)}})};
Tg=function(){g.me("ol");g.v("CSI_TICK_PAINT_TIME")?window.requestAnimationFrame&&!window.document.hidden?window.requestAnimationFrame(function(){(0,window.setTimeout)(function(){g.me("cpt");Rg()},0)}):window.document.hidden?(g.me("cpt"),Rg()):(0,window.setTimeout)(function(){g.me("cpt");
Rg()},0):Rg();
g.v("CSI_VIEWPORT")&&(Sg=lba(),Sg.then(function(a){g.me("vpl",a);Sg=null},function(){}))};
Rg=function(){Ug("init");var a=g.v("PAGE_NAME",void 0);a&&Ug("init-"+a)};
Ug=function(a){g.Ob()?Vg.push(g.Pb(g.r(g.Nb,a),0)):g.z(a)};
Wg=function(){g.Tb(Vg);Vg.length=0;Pg={};g.M(Qg);Qg.length=0;Sg&&(Sg.cancel(),Sg=null);var a=g.v("PAGE_NAME",void 0);a&&g.Nb("dispose-"+a);g.Nb("dispose")};
mba=function(){Tg()};
nba=function(){g.v("TIMING_REPORT_ON_UNLOAD")&&le(!0);Ee("u");Be("u");Wg();g.Nb("pageunload")};
Xg=function(){Re()};
Yg=function(){window.yt_spf_loaded_history=!0;g.v("EXP_LACT_HISTORY")&&Re()};
ch=function(){Zg=1;$g=ah=0;g.v("TIMING_REPORT_ON_UNLOAD")&&le(!0);Ee("n");Be("n");ye(void 0);ze();Ae(!1);pe("n");ke("mark_navigation_requested");bh(oba);g.Nb("navigate")};
gh=function(a){a=a.detail.part||a.detail.partial;g.me("nc"+ah);++ah;if(!a.data||!a.data.deferDispose){var b=1==Zg;Zg=2;b?(bh(pba),dh()):bh(qba);if(b=a.data&&a.data.swfcfg)eh(a.timing,b.args),fh(b)}};
hh=function(){g.me("np"+$g);++$g};
ih=function(a){a=a.detail.response;var b=1==Zg;Zg=3;b&&(bh(rba),dh());if(b=a.data&&a.data.swfcfg)eh(a.timing,b.args),fh(b)};
lh=function(a){g.me("nd");a=a.detail.response;g.jh=a.cacheKey;a=a.timing;var b=window._spf_state;oe("yt_nav",b&&b["nav-counter"]||0);pe("ne",a.responseStart);oe("srt",Math.max(0,a.responseStart-a.navigationStart));oe("yt_lt",a.spfCached?"hot":"warm");oe("yt_pft",+!!a.spfPrefetched);g.me("pfs",a.fetchStart);g.me("pfrs",a.responseStart);"redirectStart"in a&&te(a);bh(kh);window.document.getElementById("content").style.height="";Tg();Zg=0};
mh=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),g.Db(a)};
nh=function(a){g.Fe(g.ad({spfreload:"1",url:a.detail.url,reason:a.detail.reason}))};
tba=function(){sba();g.xb("SERVED_VIA_SPF_HISTORY",!!window.yt_spf_loaded_history);window.yt_spf_loaded_history=!1};
uba=function(){};
dh=function(){var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");Wg();var a=g.v("TIMING_ACTION"),b;for(b in g.wb)delete g.wb[b];g.xb("PREVIOUS_ACTION",a);g.m("ytplayer.config",null,void 0);if((b=g.tg())&&b.stopVideo){if(b.stopVideo(),b=b.getLastError())wg=b,(b=g.C("movie_player"))&&b.stopVideo?(b.stopVideo(),wg="recovered"):wg="missing2"}else wg="missing";sg()};
fh=function(a){"cfg"in ge(void 0)||g.me("cfg");qg(a)};
bh=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));g.Sb(oh);oh=g.Qb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var f=b.style;f.transitionDuration=f.webkitTransitionDuration=c+"ms";f.width=d+"%";g.Bb(ph);ph=g.zb(function(){b.className=e},c)},0)};
sba=function(){var a=kh[0]+50;g.Bb(ph);ph=g.zb(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
eh=function(a,b){var c=a&&a.spfCached,d=a&&a.spfPrefetched,e=[];c&&!d&&(0,g.y)(vba,function(a){a in b&&(delete b[a],e.push(a))});
g.v("EXP_DEBUG_PREFETCH")&&(e.sort(),c={a:"removeNonCacheableVideoVars",cached:c,prefetched:d,deleted:e.join("")},g.Fe(g.ad(c)))};
xba=function(a){a&&window.navigator.serviceWorker.register("/sw.js?0",{scope:"/"}).then(qh,wba)};
wba=function(){window.navigator.serviceWorker.getRegistration().then(qh)};
qh=function(a){a&&a.unregister()};
rh=function(){g.Ub.call(this,"www/base");this.B=0};
sh=function(a){(a=a.detail.name)&&Yb(a)};
g.ba=[];g.th=g.th||{};g.ea=this;pa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;g.F=Date.now||function(){return+new Date};g.ra[" "]=g.fa;g.t(g.sa,Error);g.sa.prototype.name="CustomError";var eaa,faa,gaa,haa,iaa,jaa,daa;g.Aa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;g.uh=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
g.yba=2147483648*Math.random()|0;g.Ja=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;
if(g.ka(a))return g.ka(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
g.zba=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;
0>c&&(c=Math.max(0,a.length+c));if(g.ka(a))return g.ka(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
g.y=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
g.He=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,k=g.ka(a)?a.split(""):a,l=0;l<d;l++)if(l in k){var n=k[l];
b.call(c,n,l,a)&&(e[f++]=n)}return e};
g.vh=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=g.ka(a)?a.split(""):a,k=0;k<d;k++)k in f&&(e[k]=b.call(c,f[k],k,a));
return e};
g.wh=Array.prototype.reduce?function(a,b,c,d){d&&(b=(0,g.q)(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;
(0,g.y)(a,function(c,k){e=b.call(d,e,c,k,a)});
return e};
g.xh=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;
return!1};
g.yh=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;
return!0};g.zh=g.Qa(!1);g.Ah=g.Qa(!0);g.Bh=g.Qa(null);var Za="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");a:{var Ch=g.ea.navigator;if(Ch){var Dh=Ch.userAgent;if(Dh){g.ab=Dh;break a}}g.ab=""};var pb;fb.prototype.get=function(){var a;0<this.C?(this.C--,a=this.A,this.A=a.next,a.next=null):a=this.B();return a};var mb=new fb(function(){return new ib},function(a){a.reset()},100);
hb.prototype.remove=function(){var a=null;this.A&&(a=this.A,this.A=this.A.next,this.A||(this.C=null),a.next=null);return a};
ib.prototype.set=function(a,b){this.ne=a;this.scope=b;this.next=null};
ib.prototype.reset=function(){this.next=this.scope=this.ne=null};var jb,kb=!1,lb=new hb;g.qb.prototype.Ld=!1;g.qb.prototype.isDisposed=function(){return this.Ld};
g.qb.prototype.dispose=function(){this.Ld||(this.Ld=!0,this.T())};
g.qb.prototype.T=function(){if(this.Jb)for(;this.Jb.length;)this.Jb.shift()()};g.t(g.ub,g.qb);g.h=g.ub.prototype;g.h.subscribe=function(a,b,c){var d=this.rd[a];d||(d=this.rd[a]=[]);var e=this.D;this.A[e]=a;this.A[e+1]=b;this.A[e+2]=c;this.D=e+3;d.push(e);return e};
g.h.unsubscribe=function(a,b,c){if(a=this.rd[a]){var d=this.A;if(a=g.Ia(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.sd(a)}return!1};
g.h.sd=function(a){var b=this.A[a];if(b){var c=this.rd[b];0!=this.B?(this.C.push(a),this.A[a+1]=g.fa):(c&&g.Na(c,a),delete this.A[a],delete this.A[a+1],delete this.A[a+2])}return!!b};
g.h.oa=function(a,b){var c=this.rd[a];if(c){for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];if(this.F)for(e=0;e<c.length;e++){var k=c[e];maa(this.A[k+1],this.A[k+2],d)}else{this.B++;try{for(e=0,f=c.length;e<f;e++)k=c[e],this.A[k+1].apply(this.A[k+2],d)}finally{if(this.B--,0<this.C.length&&0==this.B)for(;c=this.C.pop();)this.sd(c)}}return 0!=e}return!1};
g.h.clear=function(a){if(a){var b=this.rd[a];b&&((0,g.y)(b,this.sd,this),delete this.rd[a])}else this.A.length=0,this.rd={}};
g.h.ob=g.ca(1);g.h.T=function(){g.ub.K.T.call(this);this.clear();this.C.length=0};g.wb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};g.m("yt.config_",g.wb,void 0);g.m("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);g.Eb=window.yt&&window.yt.msgs_||g.p("window.ytcfg.msgs")||{};g.m("yt.msgs_",g.Eb,void 0);g.zd=window.performance&&window.performance.timing&&window.performance.now&&window.__yt_experimental_now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};
g.If="Microsoft Internet Explorer"==window.navigator.appName;var Aba=g.p("yt.pubsub.instance_")||new g.ub;g.ub.prototype.subscribe=g.ub.prototype.subscribe;g.ub.prototype.unsubscribeByKey=g.ub.prototype.sd;g.ub.prototype.publish=g.ub.prototype.oa;g.ub.prototype.clear=g.ub.prototype.clear;g.m("yt.pubsub.instance_",Aba,void 0);var Jb=g.p("yt.pubsub.subscribedKeys_")||{};g.m("yt.pubsub.subscribedKeys_",Jb,void 0);var Lb=g.p("yt.pubsub.topicToKeys_")||{};g.m("yt.pubsub.topicToKeys_",Lb,void 0);var Kb=g.p("yt.pubsub.isSynchronous_")||{};
g.m("yt.pubsub.isSynchronous_",Kb,void 0);var Ib=g.p("yt.pubsub.skipSubId_")||null;g.m("yt.pubsub.skipSubId_",Ib,void 0);g.h=g.Ub.prototype;g.h.MM=function(){this.Nj()||this.init()};
g.h.enable=function(){this.A=1;(0,g.y)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.MM,this),this.subscribe("dispose-"+a,this.dispose,this),g.v("PAGE_NAME")==a&&g.Wb(this))},this)};
g.h.init=function(){g.Sb(this.C);this.A=2;this.G&&this.G()};
g.h.Nj=function(){return 2==this.A};
g.h.dispose=function(){this.A=3;g.Sb(this.C);this.F&&this.F()};
g.h.disable=function(){this.A=4;this.clear();try{this.dispose()}catch(a){g.Db(a)}};
g.h.subscribe=function(a,b,c){a=g.x(a,b,c);this.D.push(a);return a};
g.h.clear=function(){g.Mb(this.D);this.D=[]};var Xb=g.p("yt.modules.registry_")||{};g.m("yt.modules.registry_",Xb,void 0);var taa={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};g.Bba=RegExp("[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.Cba=RegExp("^[^\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.Eh=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");ac.prototype.Mf=!0;ac.prototype.Oe=function(){return this.A};
ac.prototype.toString=function(){return"Const{"+this.A+"}"};
var $b={};ec.prototype.Mf=!0;var dc={};ec.prototype.Oe=function(){return this.A};
var paa=gc(""),oaa=/^([-,."'%_!# a-zA-Z0-9]+|(?:rgb|hsl)a?\([0-9.%, ]+\))$/;g.jc.prototype.Mf=!0;g.jc.prototype.Oe=function(){return this.A};
g.jc.prototype.tm=!0;g.jc.prototype.vg=function(){return 1};
var qaa=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,ic={};g.lc("about:blank");g.oc.prototype.Mf=!0;g.oc.prototype.Oe=function(){return this.A};
g.oc.prototype.tm=!0;g.oc.prototype.vg=function(){return 1};
var nc={};var vc,saa,raa,qc;g.rc.prototype.tm=!0;g.rc.prototype.vg=function(){return this.C};
g.rc.prototype.Mf=!0;g.rc.prototype.Oe=function(){return this.A};
vc=/^[a-zA-Z0-9-]+$/;saa={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};raa={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};qc={};g.Dba=g.tc("<!DOCTYPE html>",0);g.Fh=g.tc("",0);g.Gh=g.tc("<br>",0);var Dc={};var uaa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,vaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;g.Eba=Math.sign||function(a){return 0<a?1:0>a?-1:a};g.Hh="StopIteration"in g.ea?g.ea.StopIteration:{message:"StopIteration",stack:""};var Kh,Lh,Lc,Ph;g.mf=g.bb("Opera");g.E=g.cb();g.Ih=g.bb("Edge");g.Jh=g.Ih||g.E;g.lf=g.bb("Gecko")&&!(g.ya(g.ab.toLowerCase(),"webkit")&&!g.bb("Edge"))&&!(g.bb("Trident")||g.bb("MSIE"))&&!g.bb("Edge");g.Nd=g.ya(g.ab.toLowerCase(),"webkit")&&!g.bb("Edge");g.Nd&&g.bb("Mobile");g.Nf=g.bb("Macintosh");g.Mf=g.bb("Windows");g.Fba=g.bb("Linux")||g.bb("CrOS");Kh=g.ea.navigator||null;Kh&&g.ya(Kh.appVersion||"","X11");g.Gba=g.bb("Android");g.Hba=g.Jc();g.Iba=g.bb("iPad");g.Jba=g.bb("iPod");
a:{var Mh="",Nh=function(){var a=g.ab;if(g.lf)return/rv\:([^\);]+)(\)|;)/.exec(a);if(g.Ih)return/Edge\/([\d\.]+)/.exec(a);if(g.E)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(g.Nd)return/WebKit\/(\S+)/.exec(a);if(g.mf)return/(?:Version)[ \/]?(\S+)/.exec(a)}();
Nh&&(Mh=Nh?Nh[1]:"");if(g.E){var Oh=Kc();if(null!=Oh&&Oh>(0,window.parseFloat)(Mh)){Lh=String(Oh);break a}}Lh=Mh}g.Mc=Lh;Lc={};Ph=g.ea.document;g.Oc=Ph&&g.E?Kc()||("CSS1Compat"==Ph.compatMode?(0,window.parseInt)(g.Mc,10):5):void 0;g.Kba=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;g.Tc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;var id=null;"undefined"!=typeof window.XMLHttpRequest?id=function(){return new window.XMLHttpRequest}:"undefined"!=typeof window.ActiveXObject&&(id=function(){return new window.ActiveXObject("Microsoft.XMLHTTP")});var jd={"X-YouTube-Client-Name":"INNERTUBE_CONTEXT_CLIENT_NAME","X-YouTube-Client-Version":"INNERTUBE_CONTEXT_CLIENT_VERSION","X-Youtube-Identity-Token":"XSRF_TOKEN","X-YouTube-Page-CL":"PAGE_CL","X-YouTube-Page-Label":"PAGE_BUILD_LABEL","X-YouTube-Variants-Checksum":"VARIANTS_CHECKSUM"};qd.prototype.C=function(){return{context:g.pd(this.A)}};
qd.prototype.B=function(a,b,c){g.kd("//"+this.A.vO+("/youtubei/"+this.A.innertubeApiVersion+"/"+a)+"?alt=json&key="+this.A.innertubeApiKey,{headers:{"Content-Type":"application/json","X-Goog-Visitor-Id":g.v("VISITOR_DATA")},ba:b,xu:"JSON",Ac:c.Ac,X:c.X,onError:c.onError,timeout:c.timeout})};var Baa,td;Baa={log_event:"events",log_interaction:"interactions"};g.yd={};td={};g.xd=0;g.sd=g.p("yt.logging.transport.logsQueue_")||{};g.m("yt.logging.transport.logsQueue_",g.sd,void 0);g.h=g.Cd.prototype;g.h.clone=function(){return new g.Cd(this.x,this.y)};
g.h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};
g.h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
g.h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.h.scale=function(a,b){var c=g.la(b)?b:a;this.x*=a;this.y*=c;return this};g.h=g.Dd.prototype;g.h.clone=function(){return new g.Dd(this.width,this.height)};
g.h.ul=function(){return this.width*this.height};
g.h.aspectRatio=function(){return this.width/this.height};
g.h.isEmpty=function(){return!this.ul()};
g.h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.h.scale=function(a,b){var c=g.la(b)?b:a;this.width*=a;this.height*=c;return this};var Caa;Caa=!g.E||g.Pc(9);g.Lba=!g.lf&&!g.E||g.E&&g.Pc(9)||g.lf&&g.Nc("1.9.1");g.Qh=g.E&&!g.Nc("9");g.Mba=g.E||g.mf||g.Nd;g.Nba=g.E&&!g.Pc(9);var Gd={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};g.Yf=g.bb("Firefox");g.Rh=g.Jc()||g.bb("iPod");g.Sh=g.bb("iPad");g.Oba=g.bb("Android")&&!(g.db()||g.bb("Firefox")||g.bb("Opera")||g.bb("Silk"));g.Th=g.db();g.Uh=g.bb("Safari")&&!(g.db()||g.bb("Coast")||g.bb("Opera")||g.bb("Edge")||g.bb("Silk")||g.bb("Android"))&&!(g.Jc()||g.bb("iPad")||g.bb("iPod"));var Yd={},Haa=0;g.Zd.prototype.Mb=g.ca(2);g.$d.prototype.toString=function(){return this.topic};var Pba=g.p("yt.pubsub2.instance_")||new g.ub;g.ub.prototype.subscribe=g.ub.prototype.subscribe;g.ub.prototype.unsubscribeByKey=g.ub.prototype.sd;g.ub.prototype.publish=g.ub.prototype.oa;g.ub.prototype.clear=g.ub.prototype.clear;g.m("yt.pubsub2.instance_",Pba,void 0);g.Vh=g.p("yt.pubsub2.subscribedKeys_")||{};g.m("yt.pubsub2.subscribedKeys_",g.Vh,void 0);g.Wh=g.p("yt.pubsub2.topicToKeys_")||{};g.m("yt.pubsub2.topicToKeys_",g.Wh,void 0);g.Xh=g.p("yt.pubsub2.isAsync_")||{};
g.m("yt.pubsub2.isAsync_",g.Xh,void 0);g.m("yt.pubsub2.skipSubKey_",null,void 0);var De=(0,g.F)().toString();var re=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{};g.t(ce,g.Zd);var Raa=new g.$d("timing-sent",ce);var Iaa=/url\(["']?(http[^'"\)]+)['"]?\)/i;var ve={'script[name="scheduler/scheduler"]':"sj",'script[name="player/base"]':"pj",'link[rel="stylesheet"][name="www-player"]':"pc",'script[name="desktop_polymer/desktop_polymer"]':"dpj",'link[rel="import"][name="desktop_polymer"]':"dph",'script[name="mobile_polymer/mobile_polymer"]':"mpj",'link[rel="import"][name="mobile_polymer"]':"mph",'script[name="mobile-polymer-player/mobile-polymer-player"]':"mppj",'link[rel="stylesheet"][name="mobile-polymer-player"]':"mppc"},qe={ad_at:"ad_type",cpn:"client_playback_nonce",
csn:"client_screen_nonce",yt_lt:"load_type",yt_ad:"is_monetized",yt_ad_pr:"preroll_allowed",yt_red:"is_red_subscriber",yt_vis:"is_visible"},Oaa=["is_monetized","preroll_allowed","is_red_subscriber","is_visible"],ze=(0,g.q)(re.clearResourceTimings||re.webkitClearResourceTimings||re.mozClearResourceTimings||re.msClearResourceTimings||re.oClearResourceTimings||g.fa,re),ke=re.mark?(0,g.q)(re.mark,re):g.fa;re.measure&&(0,g.q)(re.measure,re);var Je;g.Qba=g.Nd?"webkit":g.lf?"moz":g.E?"ms":g.mf?"o":"";Je=g.p("yt.dom.getNextId_");if(!Je){Je=function(){return++Rba};
g.m("yt.dom.getNextId_",Je,void 0);var Rba=0};g.Me.prototype.preventDefault=function(){this.event&&(this.event.returnValue=!1,this.event.preventDefault&&this.event.preventDefault())};
g.Me.prototype.stopPropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopPropagation&&this.event.stopPropagation())};
g.Me.prototype.stopImmediatePropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopImmediatePropagation&&this.event.stopImmediatePropagation())};
var Saa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1,webkitMovementX:1,webkitMovementY:1};g.Ne=g.p("yt.events.listeners_")||{};g.m("yt.events.listeners_",g.Ne,void 0);var Pe=g.p("yt.events.counter_")||{count:0};g.m("yt.events.counter_",Pe,void 0);var Taa={enablejsapi:1},Uaa={},Vaa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};Ue.prototype.clone=function(){var a=new Ue,b;for(b in this)if(this.hasOwnProperty(b)){var c=this[b];"object"==g.ha(c)?a[b]=g.Ya(c):a[b]=c}return a};g.We=null;g.af=/\s*;\s*/;g.h=g.$e.prototype;g.h.isEnabled=function(){return window.navigator.cookieEnabled};
g.h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');g.da(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,g.F)()+1E3*c)).toUTCString();this.A.cookie=a+"="+b+e+d+c+f};
g.h.get=function(a,b){for(var c=a+"=",d=(this.A.cookie||"").split(g.af),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};
g.h.remove=function(a,b,c){var d=g.da(this.get(a));this.set(a,"",0,b,c);return d};
g.h.Kb=g.ca(3);g.h.jb=g.ca(4);g.h.isEmpty=function(){return!this.A.cookie};
g.h.ob=g.ca(0);g.h.me=g.ca(5);g.h.clear=function(){for(var a=g.bf(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
g.cf=new g.$e("undefined"==typeof window.document?null:window.document);g.cf.C=3950;g.Yh=g.E?"focusin":"DOMFocusIn";g.Zh=g.E?"focusout":"DOMFocusOut";g.$h=g.Nd?"webkitTransitionEnd":g.mf?"otransitionend":"transitionend";g.h=g.pf.prototype;g.h.getHeight=function(){return this.bottom-this.top};
g.h.clone=function(){return new g.pf(this.top,this.right,this.bottom,this.left)};
g.h.contains=function(a){return g.qf(this,a)};
g.h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
g.h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.h.scale=function(a,b){var c=g.la(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};g.h=g.rf.prototype;g.h.clone=function(){return new g.rf(this.left,this.top,this.width,this.height)};
g.h.contains=function(a){return a instanceof g.rf?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
g.h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.h.scale=function(a,b){var c=g.la(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};var sf;sf={};g.ai=g.lf?"MozUserSelect":g.Nd||g.Ih?"WebkitUserSelect":null;g.ga(g.Af);g.zf=g.p("yt.prefs.UserPrefs.prefs_")||{};g.m("yt.prefs.UserPrefs.prefs_",g.zf,void 0);g.h=g.Af.prototype;g.h.get=function(a,b){Cf(a);Bf(a);var c=void 0!==g.zf[a]?g.zf[a].toString():null;return null!=c?c:b?b:""};
g.h.set=function(a,b){Cf(a);Bf(a);if(null==b)throw"ExpectedNotNull";g.zf[a]=b.toString()};
g.h.remove=function(a){Cf(a);Bf(a);delete g.zf[a]};
g.h.save=function(){var a;a=[];for(var b in g.zf)a.push(b+"="+(0,window.escape)(g.zf[b]));a=a.join("&");g.df("PREF",a,63072E3)};
g.h.clear=function(){g.zf={}};g.bi=g.Ra(function(){if(g.E)return g.Nc("10.0");var a=window.document.createElement("DIV"),b=g.of(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");g.zc(a,g.xc("div",{style:c}));return""!=g.uf(a.firstChild,"transition")});g.ga(g.Jf);g.Jf.prototype.getVersion=function(){return[this.major,this.minor,this.A]};var Zaa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var gg;var ci=g.ab,ci=ci.toLowerCase();if(g.ya(ci,"android")){var di=ci.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(di)gg=Number(di[1]);else{var ei={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},fi=ci.match("("+g.Ta(ei).join("|")+")");gg=fi?ei[fi[0]]:0}}else gg=void 0;var bba=['video/mp4; codecs="avc1.42001E, mp4a.40.2"','video/webm; codecs="vp8.0, vorbis"'],cba=['audio/mp4; codecs="mp4a.40.2"'];g.t(g.Uf,g.qb);g.Uf.prototype.Ua=g.ca(6);g.Uf.prototype.T=function(){Wf(this);g.Uf.K.T.call(this)};var $aa={"api.invalidparam":2,auth:150,"drm.auth":150,heartbeat:150,"html5.unsupportedads":5,"fmt.noneavailable":5,"fmt.decode":5,"fmt.unplayable":5,"html5.missingapi":5,"html5.unsupportedlive":5,"drm.unavailable":5};g.t(Zf,g.qb);var aba=["drm.unavailable","fmt.noneavailable","html5.missingapi","html5.unsupportedads","html5.unsupportedlive"];g.h=Zf.prototype;g.h.getId=function(){return this.ia};
g.h.vo=function(a,b){this.isDisposed()||(ag(this,a),eg(this,b),this.L&&bg(this))};
g.h.az=function(){return this.kb};
g.h.tO=function(){if(!this.aa){var a=hg(this);a&&"html5"==jg(this)?(this.F="html5",this.L||this.Pg()):(kg(this),this.F="html5",a&&this.M?(this.D.appendChild(this.M),this.Pg()):(this.A.loaded=!0,this.R=(0,g.q)(function(){var a=this.D,c=this.A.clone();g.p("yt.player.Application.create")(a,c);this.Pg()},this),this.aa=!0,a?this.R():(g.Fc(this.A.assets.js,this.R),g.Tf(this.A.assets.css))))}};
g.h.sO=function(){var a=this.A.clone();if(!this.G){var b=dg(this);b&&(this.G=window.document.createElement("span"),this.G.tabIndex=0,Vf(this.ea,this.G,"focus",this.vt),this.W=window.document.createElement("span"),this.W.tabIndex=0,Vf(this.ea,this.W,"focus",this.vt),g.Sd(this.G,b),g.Td(this.W,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==jg(this)?(this.F="flash",this.L||Sf(a,!1,(0,g.q)(this.Pg,this))):(kg(this),this.F="flash",this.A.loaded=!0,g.Rf(this.D,a),
this.Pg())};
g.h.vt=function(){dg(this).focus()};
g.h.Pg=function(){if(!this.isDisposed()){var a=dg(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(f){}if(b)if(this.aa=!1,a.isNotServable&&a.isNotServable(this.A.args.video_id))fg(this);else{Xf(this);this.L=!0;a=dg(this);a.addEventListener&&(this.U=ig(this,a,"addEventListener"));a.removeEventListener&&(this.Qa=ig(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),c=0;c<b.length;c++){var d=b[c];this.api[d]||(this.api[d]=ig(this,
a,d))}for(var e in this.B)this.U(e,this.B[e]);bg(this);this.Wa&&this.Wa(this.api);this.Y.oa("onReady",this.api)}else this.Db=g.zb((0,g.q)(this.Pg,this),50)}};
g.h.IO=function(){return this.L};
g.h.fe=function(a,b){if(!this.isDisposed()){var c=$f(this,b);if(c){if(!g.Ka(this.fc,a)&&!this.B[a]){var d=dba(this,a);this.U&&this.U(a,d)}this.Y.subscribe(a,c);"onReady"==a&&this.L&&g.zb(g.r(c,this.api),0)}}};
g.h.zM=function(a,b){if(!this.isDisposed()){var c=$f(this,b);c&&this.Y.unsubscribe(a,c)}};
g.h.ey=function(a){a=a?Faa:Eaa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.G||b==this.W||(b.focus(),b!=window.document.activeElement));)b=a(b)};
g.h.Uo=function(a){g.z("a11y-announce",a)};
g.h.BI=function(a){fg(this,a)};
g.h.EI=function(a){g.z("WATCH_LATER_VIDEO_ADDED",a)};
g.h.FI=function(a){g.z("WATCH_LATER_VIDEO_REMOVED",a)};
g.h.lI=function(){this.gb||(g.Th?(this.ab=g.Md(window.document),Vf(this.H,window,"scroll",this.JK),Vf(this.H,this.D,"touchmove",this.qK)):(Vf(this.H,this.D,"mousewheel",this.Kt),Vf(this.H,this.D,"wheel",this.Kt)),this.gb=!0)};
g.h.mI=function(){Wf(this.H);this.gb=!1};
g.h.Kt=function(a){g.Qe(a)};
g.h.JK=function(){window.scrollTo(this.ab.x,this.ab.y)};
g.h.qK=function(a){a.preventDefault()};
g.h.uO=function(){kg(this);this.F="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');
b=this.A.messages.player_fallback||a;a=g.C("player-unavailable");g.C("unavailable-submessage")&&a&&(g.C("unavailable-submessage").innerHTML=b,(b=g.D("icon",a))&&g.Cc(b,"icon")&&(b.src=g.A(b,"icon")),g.yf(a,!0),g.I(g.C("player"),"off-screen-trigger"))};
g.h.Tz=function(){return this.F||jg(this)};
g.h.Dz=function(){return this.rb};
g.h.cancel=function(){this.R&&g.Gc(this.A.assets.js,this.R);g.Bb(this.Db);this.aa=!1};
g.h.T=function(){kg(this);if(this.M&&this.A)try{this.M.destroy()}catch(b){g.Db(b)}this.Ya=null;for(var a in this.B)g.ea[this.B[a]]=null;this.kb=this.A=this.api=null;delete this.D;delete this.O;Zf.K.T.call(this)};g.mg={};g.lg="player_uid_"+(1E9*Math.random()>>>0);var Sba=g.p("yt.abuse.botguardInitialized")||Xe;g.m("yt.abuse.botguardInitialized",Sba,void 0);var Tba=g.p("yt.abuse.invokeBotguard")||g.Ye;g.m("yt.abuse.invokeBotguard",Tba,void 0);var Uba=g.p("yt.abuse.dclkstatus.checkDclkStatus")||Ze;g.m("yt.abuse.dclkstatus.checkDclkStatus",Uba,void 0);var Vba=g.p("yt.player.exports.navigate")||g.kf;g.m("yt.player.exports.navigate",Vba,void 0);var Wba=g.p("yt.player.embed")||g.ng;g.m("yt.player.embed",Wba,void 0);var Xba=g.p("yt.player.getPlayerByElement")||g.og;
g.m("yt.player.getPlayerByElement",Xba,void 0);var Yba=g.p("yt.util.activity.init")||g.Se;g.m("yt.util.activity.init",Yba,void 0);var Zba=g.p("yt.util.activity.getTimeSinceActive")||g.Te;g.m("yt.util.activity.getTimeSinceActive",Zba,void 0);var $ba=g.p("yt.util.activity.setTimestamp")||Re;g.m("yt.util.activity.setTimestamp",$ba,void 0);var rg,wg;g.vg=null;wg="";Bg.prototype.reset=function(){this.context=this.C=this.D=this.A=null;this.B=!1};
var Cg=new fb(function(){return new Bg},function(a){a.reset()},100);
g.Ag.prototype.then=function(a,b,c){return g.Mg(this,g.ma(a)?a:null,g.ma(b)?b:null,c)};
g.xg(g.Ag);g.Ag.prototype.cancel=function(a){0==this.A&&nb(function(){var b=new Lg(a);Gg(this,b)},this)};
g.Ag.prototype.W=function(a){this.A=0;g.zg(this,2,a)};
g.Ag.prototype.H=function(a){this.A=0;g.zg(this,3,a)};
g.Ag.prototype.O=function(){for(var a;a=Hg(this);)Ig(this,a,this.A,this.L);this.G=!1};
var Og=eb;g.t(Lg,g.sa);Lg.prototype.name="cancel";var Pg={},Qg=[];var Sg=null,Vg=[];var Zg,ph,oh,ah,$g,vba,oba,rba,pba,qba,kh;ah=0;$g=0;vba=["server_prefetched_vast","vmap"];oba=[900,60,"waiting"];rba=[500,99,"waiting"];pba=[300,60,"waiting"];qba=[400,99,"waiting"];kh=[300,101,"done"];window.yt=window.yt||{};g.m("yt.setConfig",g.xb,void 0);g.m("yt.pushConfigArray",function(a,b){var c=g.v(a,void 0);c?c.push(b):g.xb(a,[b])},void 0);
g.m("yt.getConfig",g.v,void 0);g.m("yt.hasMsg",g.Fb,void 0);g.m("yt.pubsub.publish",g.z,void 0);g.m("yt.pubsub.subscribe",g.x,void 0);g.m("yt.setMsg",function(a){vb(g.Eb,arguments)},void 0);
g.m("yt.setGoogMsg",function(a){vb(g.Eb,arguments)},void 0);
g.m("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+Math.round(a[e]));c.rt=d.join(",");for(var f in b)"_"!=f.charAt(0)&&(c[f]=b[f]);a=g.v("TIMING_INFO",{});"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);xe(c)},void 0);
g.m("ytcsi.tick",g.me,void 0);g.t(rh,g.Ub);
rh.prototype.enable=function(){window.onload=mba;window.onunload=nba;window.onerror=naa;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfclick",Xg),window.addEventListener("spfhistory",Yg),window.addEventListener("spfrequest",ch),window.addEventListener("spfpartprocess",gh),window.addEventListener("spfpartdone",hh),window.addEventListener("spfprocess",ih),window.addEventListener("spfdone",lh),window.addEventListener("spferror",mh),window.addEventListener("spfreload",
nh),window.addEventListener("spfjsbeforeunload",sh)),a.config=a.config||{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",tba),this.subscribe("dispose",uba)):window.spf.dispose();
this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
rh.prototype.init=function(){rh.K.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&g.v("PAGEFRAME_JS")?(b=g.v("PAGEFRAME_JS",void 0),c=function(){window.ytPageFrameLoaded=!0;g.p("ytbin.www.pageframe.setup")()}):a&&(a=g.p("yt.www.masthead.loadSearchbox"))&&a();
var a=g.v("JS_COMMON_MODULE"),d=g.v("JS_PAGE_MODULES");d||(d=[a]);a=g.v("JS_DELAY_LOAD",0);0<a?(g.Bb(this.B),this.B=g.zb(function(){b&&g.Fc(b,c);window.spf.script.require(d)},a)):(b&&g.Fc(b,c),window.spf.script.require(d));
fba();Qaa();Naa();g.m("yt.timing.ready_",!0,void 0);le(!1);"serviceWorker"in window.navigator&&"https:"==window.location.protocol&&(g.Hc("service_worker_enabled")?window.navigator.serviceWorker.register("/sw.js",{scope:"/"}):window.navigator.serviceWorker.controller&&window.navigator.serviceWorker.getRegistration().then(xba))};
rh.prototype.dispose=function(){g.Bb(this.B);var a=g.p("ytbin.www.pageframe.cancelSetup");a&&a();g.Cb(rg);if(a=g.tg())a.removeEventListener("onReady",sg),a.removeEventListener("onStateChange",sg);g.m("yt.timing.ready_",!1,void 0);rh.K.dispose.call(this)};
rh.prototype.disable=function(){rh.K.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfclick",Xg),window.removeEventListener("spfhistory",Yg),window.removeEventListener("spfrequest",ch),window.removeEventListener("spfpartprocess",gh),window.removeEventListener("spfpartdone",hh),window.removeEventListener("spfprocess",ih),window.removeEventListener("spfdone",lh),window.removeEventListener("spferror",mh),window.removeEventListener("spfreload",nh),window.removeEventListener("spfjsbeforeunload",
sh));window.onload=null;window.onunload=null;window.onerror=null};
g.Zb(new rh);})(_yt_www);
